server:
  port: 8081
  servlet:
    context-path: /storage

spring:
  application:
    name: storage
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1
    url: jdbc:postgresql://localhost:5432/storage?currentScheme=public
  liquibase:
    change-log: classpath:db/master.xml
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092

kafka:
  server: localhost:9092
  group:
    id: storage-group